/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.vertigo.estagio.campanha.model.impl;

import br.com.vertigo.estagio.campanha.model.Premio;
import br.com.vertigo.estagio.campanha.model.PremioModel;
import br.com.vertigo.estagio.campanha.model.PremioSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Premio service. Represents a row in the &quot;FOO_Premio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PremioModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PremioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PremioImpl
 * @generated
 */
@JSON(strict = true)
public class PremioModelImpl
	extends BaseModelImpl<Premio> implements PremioModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a premio model instance should use the <code>Premio</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_Premio";

	public static final Object[][] TABLE_COLUMNS = {
		{"premioId", Types.BIGINT}, {"promocaoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nome", Types.VARCHAR}, {"descricao", Types.VARCHAR},
		{"fileEntryId", Types.BIGINT}, {"fileUrl", Types.VARCHAR},
		{"userIdPremiado", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("premioId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("promocaoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descricao", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userIdPremiado", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_Premio (premioId LONG not null primary key,promocaoId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nome VARCHAR(75) null,descricao VARCHAR(75) null,fileEntryId LONG,fileUrl VARCHAR(1024) null,userIdPremiado LONG)";

	public static final String TABLE_SQL_DROP = "drop table FOO_Premio";

	public static final String ORDER_BY_JPQL = " ORDER BY premio.premioId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_Premio.premioId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long GROUPID_COLUMN_BITMASK = 1L;

	public static final long PREMIOID_COLUMN_BITMASK = 2L;

	public static final long PROMOCAOID_COLUMN_BITMASK = 4L;

	public static final long USERIDPREMIADO_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Premio toModel(PremioSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Premio model = new PremioImpl();

		model.setPremioId(soapModel.getPremioId());
		model.setPromocaoId(soapModel.getPromocaoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setNome(soapModel.getNome());
		model.setDescricao(soapModel.getDescricao());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setFileUrl(soapModel.getFileUrl());
		model.setUserIdPremiado(soapModel.getUserIdPremiado());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Premio> toModels(PremioSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Premio> models = new ArrayList<Premio>(soapModels.length);

		for (PremioSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PremioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _premioId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPremioId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _premioId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Premio.class;
	}

	@Override
	public String getModelClassName() {
		return Premio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Premio, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Premio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Premio, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Premio)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Premio, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Premio, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Premio)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Premio, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Premio, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Premio>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Premio.class.getClassLoader(), Premio.class, ModelWrapper.class);

		try {
			Constructor<Premio> constructor =
				(Constructor<Premio>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Premio, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Premio, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Premio, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Premio, Object>>();
		Map<String, BiConsumer<Premio, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Premio, ?>>();

		attributeGetterFunctions.put("premioId", Premio::getPremioId);
		attributeSetterBiConsumers.put(
			"premioId", (BiConsumer<Premio, Long>)Premio::setPremioId);
		attributeGetterFunctions.put("promocaoId", Premio::getPromocaoId);
		attributeSetterBiConsumers.put(
			"promocaoId", (BiConsumer<Premio, Long>)Premio::setPromocaoId);
		attributeGetterFunctions.put("groupId", Premio::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Premio, Long>)Premio::setGroupId);
		attributeGetterFunctions.put("companyId", Premio::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Premio, Long>)Premio::setCompanyId);
		attributeGetterFunctions.put("userId", Premio::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Premio, Long>)Premio::setUserId);
		attributeGetterFunctions.put("userName", Premio::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Premio, String>)Premio::setUserName);
		attributeGetterFunctions.put("createDate", Premio::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Premio, Date>)Premio::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Premio::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Premio, Date>)Premio::setModifiedDate);
		attributeGetterFunctions.put("nome", Premio::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Premio, String>)Premio::setNome);
		attributeGetterFunctions.put("descricao", Premio::getDescricao);
		attributeSetterBiConsumers.put(
			"descricao", (BiConsumer<Premio, String>)Premio::setDescricao);
		attributeGetterFunctions.put("fileEntryId", Premio::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId", (BiConsumer<Premio, Long>)Premio::setFileEntryId);
		attributeGetterFunctions.put("fileUrl", Premio::getFileUrl);
		attributeSetterBiConsumers.put(
			"fileUrl", (BiConsumer<Premio, String>)Premio::setFileUrl);
		attributeGetterFunctions.put(
			"userIdPremiado", Premio::getUserIdPremiado);
		attributeSetterBiConsumers.put(
			"userIdPremiado",
			(BiConsumer<Premio, Long>)Premio::setUserIdPremiado);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getPremioId() {
		return _premioId;
	}

	@Override
	public void setPremioId(long premioId) {
		_columnBitmask = -1L;

		if (!_setOriginalPremioId) {
			_setOriginalPremioId = true;

			_originalPremioId = _premioId;
		}

		_premioId = premioId;
	}

	public long getOriginalPremioId() {
		return _originalPremioId;
	}

	@JSON
	@Override
	public long getPromocaoId() {
		return _promocaoId;
	}

	@Override
	public void setPromocaoId(long promocaoId) {
		_columnBitmask |= PROMOCAOID_COLUMN_BITMASK;

		if (!_setOriginalPromocaoId) {
			_setOriginalPromocaoId = true;

			_originalPromocaoId = _promocaoId;
		}

		_promocaoId = promocaoId;
	}

	public long getOriginalPromocaoId() {
		return _originalPromocaoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_nome = nome;
	}

	@JSON
	@Override
	public String getDescricao() {
		if (_descricao == null) {
			return "";
		}
		else {
			return _descricao;
		}
	}

	@Override
	public void setDescricao(String descricao) {
		_descricao = descricao;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public String getFileUrl() {
		if (_fileUrl == null) {
			return "";
		}
		else {
			return _fileUrl;
		}
	}

	@Override
	public void setFileUrl(String fileUrl) {
		_fileUrl = fileUrl;
	}

	@JSON
	@Override
	public long getUserIdPremiado() {
		return _userIdPremiado;
	}

	@Override
	public void setUserIdPremiado(long userIdPremiado) {
		_columnBitmask |= USERIDPREMIADO_COLUMN_BITMASK;

		if (!_setOriginalUserIdPremiado) {
			_setOriginalUserIdPremiado = true;

			_originalUserIdPremiado = _userIdPremiado;
		}

		_userIdPremiado = userIdPremiado;
	}

	public long getOriginalUserIdPremiado() {
		return _originalUserIdPremiado;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Premio.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Premio toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Premio>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PremioImpl premioImpl = new PremioImpl();

		premioImpl.setPremioId(getPremioId());
		premioImpl.setPromocaoId(getPromocaoId());
		premioImpl.setGroupId(getGroupId());
		premioImpl.setCompanyId(getCompanyId());
		premioImpl.setUserId(getUserId());
		premioImpl.setUserName(getUserName());
		premioImpl.setCreateDate(getCreateDate());
		premioImpl.setModifiedDate(getModifiedDate());
		premioImpl.setNome(getNome());
		premioImpl.setDescricao(getDescricao());
		premioImpl.setFileEntryId(getFileEntryId());
		premioImpl.setFileUrl(getFileUrl());
		premioImpl.setUserIdPremiado(getUserIdPremiado());

		premioImpl.resetOriginalValues();

		return premioImpl;
	}

	@Override
	public int compareTo(Premio premio) {
		int value = 0;

		if (getPremioId() < premio.getPremioId()) {
			value = -1;
		}
		else if (getPremioId() > premio.getPremioId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Premio)) {
			return false;
		}

		Premio premio = (Premio)obj;

		long primaryKey = premio.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		PremioModelImpl premioModelImpl = this;

		premioModelImpl._originalPremioId = premioModelImpl._premioId;

		premioModelImpl._setOriginalPremioId = false;

		premioModelImpl._originalPromocaoId = premioModelImpl._promocaoId;

		premioModelImpl._setOriginalPromocaoId = false;

		premioModelImpl._originalGroupId = premioModelImpl._groupId;

		premioModelImpl._setOriginalGroupId = false;

		premioModelImpl._setModifiedDate = false;

		premioModelImpl._originalUserIdPremiado =
			premioModelImpl._userIdPremiado;

		premioModelImpl._setOriginalUserIdPremiado = false;

		premioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Premio> toCacheModel() {
		PremioCacheModel premioCacheModel = new PremioCacheModel();

		premioCacheModel.premioId = getPremioId();

		premioCacheModel.promocaoId = getPromocaoId();

		premioCacheModel.groupId = getGroupId();

		premioCacheModel.companyId = getCompanyId();

		premioCacheModel.userId = getUserId();

		premioCacheModel.userName = getUserName();

		String userName = premioCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			premioCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			premioCacheModel.createDate = createDate.getTime();
		}
		else {
			premioCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			premioCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			premioCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		premioCacheModel.nome = getNome();

		String nome = premioCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			premioCacheModel.nome = null;
		}

		premioCacheModel.descricao = getDescricao();

		String descricao = premioCacheModel.descricao;

		if ((descricao != null) && (descricao.length() == 0)) {
			premioCacheModel.descricao = null;
		}

		premioCacheModel.fileEntryId = getFileEntryId();

		premioCacheModel.fileUrl = getFileUrl();

		String fileUrl = premioCacheModel.fileUrl;

		if ((fileUrl != null) && (fileUrl.length() == 0)) {
			premioCacheModel.fileUrl = null;
		}

		premioCacheModel.userIdPremiado = getUserIdPremiado();

		return premioCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Premio, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Premio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Premio, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Premio)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Premio, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Premio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Premio, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Premio)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Premio>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _premioId;
	private long _originalPremioId;
	private boolean _setOriginalPremioId;
	private long _promocaoId;
	private long _originalPromocaoId;
	private boolean _setOriginalPromocaoId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nome;
	private String _descricao;
	private long _fileEntryId;
	private String _fileUrl;
	private long _userIdPremiado;
	private long _originalUserIdPremiado;
	private boolean _setOriginalUserIdPremiado;
	private long _columnBitmask;
	private Premio _escapedModel;

}