/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.testimonial.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.testimonial.model.Testament;
import com.liferay.testimonial.service.TestamentLocalService;
import com.liferay.testimonial.service.persistence.ContactPersistence;
import com.liferay.testimonial.service.persistence.TestamentPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the testament local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.testimonial.service.impl.TestamentLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.testimonial.service.impl.TestamentLocalServiceImpl
 * @generated
 */
public abstract class TestamentLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, TestamentLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TestamentLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.testimonial.service.TestamentLocalServiceUtil</code>.
	 */

	/**
	 * Adds the testament to the database. Also notifies the appropriate model listeners.
	 *
	 * @param testament the testament
	 * @return the testament that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Testament addTestament(Testament testament) {
		testament.setNew(true);

		return testamentPersistence.update(testament);
	}

	/**
	 * Creates a new testament with the primary key. Does not add the testament to the database.
	 *
	 * @param testamentId the primary key for the new testament
	 * @return the new testament
	 */
	@Override
	@Transactional(enabled = false)
	public Testament createTestament(long testamentId) {
		return testamentPersistence.create(testamentId);
	}

	/**
	 * Deletes the testament with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param testamentId the primary key of the testament
	 * @return the testament that was removed
	 * @throws PortalException if a testament with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Testament deleteTestament(long testamentId) throws PortalException {
		return testamentPersistence.remove(testamentId);
	}

	/**
	 * Deletes the testament from the database. Also notifies the appropriate model listeners.
	 *
	 * @param testament the testament
	 * @return the testament that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Testament deleteTestament(Testament testament) {
		return testamentPersistence.remove(testament);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Testament.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return testamentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.testimonial.model.impl.TestamentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return testamentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.testimonial.model.impl.TestamentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return testamentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return testamentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return testamentPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Testament fetchTestament(long testamentId) {
		return testamentPersistence.fetchByPrimaryKey(testamentId);
	}

	/**
	 * Returns the testament matching the UUID and group.
	 *
	 * @param uuid the testament's UUID
	 * @param groupId the primary key of the group
	 * @return the matching testament, or <code>null</code> if a matching testament could not be found
	 */
	@Override
	public Testament fetchTestamentByUuidAndGroupId(String uuid, long groupId) {
		return testamentPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the testament with the primary key.
	 *
	 * @param testamentId the primary key of the testament
	 * @return the testament
	 * @throws PortalException if a testament with the primary key could not be found
	 */
	@Override
	public Testament getTestament(long testamentId) throws PortalException {
		return testamentPersistence.findByPrimaryKey(testamentId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(testamentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Testament.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("testamentId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			testamentLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Testament.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"testamentId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(testamentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Testament.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("testamentId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<Testament>() {

				@Override
				public void performAction(Testament testament)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, testament);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(Testament.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return testamentLocalService.deleteTestament((Testament)persistedModel);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return testamentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the testaments matching the UUID and company.
	 *
	 * @param uuid the UUID of the testaments
	 * @param companyId the primary key of the company
	 * @return the matching testaments, or an empty list if no matches were found
	 */
	@Override
	public List<Testament> getTestamentsByUuidAndCompanyId(
		String uuid, long companyId) {

		return testamentPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of testaments matching the UUID and company.
	 *
	 * @param uuid the UUID of the testaments
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of testaments
	 * @param end the upper bound of the range of testaments (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching testaments, or an empty list if no matches were found
	 */
	@Override
	public List<Testament> getTestamentsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<Testament> orderByComparator) {

		return testamentPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the testament matching the UUID and group.
	 *
	 * @param uuid the testament's UUID
	 * @param groupId the primary key of the group
	 * @return the matching testament
	 * @throws PortalException if a matching testament could not be found
	 */
	@Override
	public Testament getTestamentByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return testamentPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the testaments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.testimonial.model.impl.TestamentModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of testaments
	 * @param end the upper bound of the range of testaments (not inclusive)
	 * @return the range of testaments
	 */
	@Override
	public List<Testament> getTestaments(int start, int end) {
		return testamentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of testaments.
	 *
	 * @return the number of testaments
	 */
	@Override
	public int getTestamentsCount() {
		return testamentPersistence.countAll();
	}

	/**
	 * Updates the testament in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param testament the testament
	 * @return the testament that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Testament updateTestament(Testament testament) {
		return testamentPersistence.update(testament);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			TestamentLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		testamentLocalService = (TestamentLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TestamentLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Testament.class;
	}

	protected String getModelClassName() {
		return Testament.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = testamentPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected ContactPersistence contactPersistence;

	protected TestamentLocalService testamentLocalService;

	@Reference
	protected TestamentPersistence testamentPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}