/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.testimonial.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Testament service. Represents a row in the &quot;TTM_Testament&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.testimonial.model.impl.TestamentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.testimonial.model.impl.TestamentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Testament
 * @generated
 */
@ProviderType
public interface TestamentModel
	extends BaseModel<Testament>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testament model instance should use the {@link Testament} interface instead.
	 */

	/**
	 * Returns the primary key of this testament.
	 *
	 * @return the primary key of this testament
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this testament.
	 *
	 * @param primaryKey the primary key of this testament
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this testament.
	 *
	 * @return the uuid of this testament
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this testament.
	 *
	 * @param uuid the uuid of this testament
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the testament ID of this testament.
	 *
	 * @return the testament ID of this testament
	 */
	public long getTestamentId();

	/**
	 * Sets the testament ID of this testament.
	 *
	 * @param testamentId the testament ID of this testament
	 */
	public void setTestamentId(long testamentId);

	/**
	 * Returns the group ID of this testament.
	 *
	 * @return the group ID of this testament
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this testament.
	 *
	 * @param groupId the group ID of this testament
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this testament.
	 *
	 * @return the company ID of this testament
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this testament.
	 *
	 * @param companyId the company ID of this testament
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this testament.
	 *
	 * @return the user ID of this testament
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this testament.
	 *
	 * @param userId the user ID of this testament
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this testament.
	 *
	 * @return the user uuid of this testament
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this testament.
	 *
	 * @param userUuid the user uuid of this testament
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this testament.
	 *
	 * @return the user name of this testament
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this testament.
	 *
	 * @param userName the user name of this testament
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this testament.
	 *
	 * @return the create date of this testament
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this testament.
	 *
	 * @param createDate the create date of this testament
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this testament.
	 *
	 * @return the modified date of this testament
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this testament.
	 *
	 * @param modifiedDate the modified date of this testament
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this testament.
	 *
	 * @return the title of this testament
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this testament.
	 *
	 * @param title the title of this testament
	 */
	public void setTitle(String title);

	/**
	 * Returns the message of this testament.
	 *
	 * @return the message of this testament
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this testament.
	 *
	 * @param message the message of this testament
	 */
	public void setMessage(String message);

	/**
	 * Returns the due date of this testament.
	 *
	 * @return the due date of this testament
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this testament.
	 *
	 * @param dueDate the due date of this testament
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the contact ID of this testament.
	 *
	 * @return the contact ID of this testament
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this testament.
	 *
	 * @param contactId the contact ID of this testament
	 */
	public void setContactId(long contactId);

}