/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.vertigo.estagio.campanha.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Participante service. Represents a row in the &quot;FOO_Participante&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.vertigo.estagio.campanha.model.impl.ParticipanteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.vertigo.estagio.campanha.model.impl.ParticipanteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Participante
 * @generated
 */
@ProviderType
public interface ParticipanteModel
	extends BaseModel<Participante>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a participante model instance should use the {@link Participante} interface instead.
	 */

	/**
	 * Returns the primary key of this participante.
	 *
	 * @return the primary key of this participante
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this participante.
	 *
	 * @param primaryKey the primary key of this participante
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the participante ID of this participante.
	 *
	 * @return the participante ID of this participante
	 */
	public long getParticipanteId();

	/**
	 * Sets the participante ID of this participante.
	 *
	 * @param participanteId the participante ID of this participante
	 */
	public void setParticipanteId(long participanteId);

	/**
	 * Returns the promocao ID of this participante.
	 *
	 * @return the promocao ID of this participante
	 */
	public long getPromocaoId();

	/**
	 * Sets the promocao ID of this participante.
	 *
	 * @param promocaoId the promocao ID of this participante
	 */
	public void setPromocaoId(long promocaoId);

	/**
	 * Returns the group ID of this participante.
	 *
	 * @return the group ID of this participante
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this participante.
	 *
	 * @param groupId the group ID of this participante
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this participante.
	 *
	 * @return the company ID of this participante
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this participante.
	 *
	 * @param companyId the company ID of this participante
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this participante.
	 *
	 * @return the user ID of this participante
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this participante.
	 *
	 * @param userId the user ID of this participante
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this participante.
	 *
	 * @return the user uuid of this participante
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this participante.
	 *
	 * @param userUuid the user uuid of this participante
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this participante.
	 *
	 * @return the user name of this participante
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this participante.
	 *
	 * @param userName the user name of this participante
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this participante.
	 *
	 * @return the create date of this participante
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this participante.
	 *
	 * @param createDate the create date of this participante
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this participante.
	 *
	 * @return the modified date of this participante
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this participante.
	 *
	 * @param modifiedDate the modified date of this participante
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email of this participante.
	 *
	 * @return the email of this participante
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this participante.
	 *
	 * @param email the email of this participante
	 */
	public void setEmail(String email);

	/**
	 * Returns the primeiro nome of this participante.
	 *
	 * @return the primeiro nome of this participante
	 */
	@AutoEscape
	public String getPrimeiroNome();

	/**
	 * Sets the primeiro nome of this participante.
	 *
	 * @param primeiroNome the primeiro nome of this participante
	 */
	public void setPrimeiroNome(String primeiroNome);

	/**
	 * Returns the ultimo nome of this participante.
	 *
	 * @return the ultimo nome of this participante
	 */
	@AutoEscape
	public String getUltimoNome();

	/**
	 * Sets the ultimo nome of this participante.
	 *
	 * @param ultimoNome the ultimo nome of this participante
	 */
	public void setUltimoNome(String ultimoNome);

}