/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.vertigo.estagio.campanha.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Premios service. Represents a row in the &quot;FOO_Premios&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.vertigo.estagio.campanha.model.impl.PremiosModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.vertigo.estagio.campanha.model.impl.PremiosImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Premios
 * @generated
 */
@ProviderType
public interface PremiosModel
	extends BaseModel<Premios>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a premios model instance should use the {@link Premios} interface instead.
	 */

	/**
	 * Returns the primary key of this premios.
	 *
	 * @return the primary key of this premios
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this premios.
	 *
	 * @param primaryKey the primary key of this premios
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the premios ID of this premios.
	 *
	 * @return the premios ID of this premios
	 */
	public long getPremiosId();

	/**
	 * Sets the premios ID of this premios.
	 *
	 * @param premiosId the premios ID of this premios
	 */
	public void setPremiosId(long premiosId);

	/**
	 * Returns the promocao ID of this premios.
	 *
	 * @return the promocao ID of this premios
	 */
	public long getPromocaoId();

	/**
	 * Sets the promocao ID of this premios.
	 *
	 * @param promocaoId the promocao ID of this premios
	 */
	public void setPromocaoId(long promocaoId);

	/**
	 * Returns the group ID of this premios.
	 *
	 * @return the group ID of this premios
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this premios.
	 *
	 * @param groupId the group ID of this premios
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this premios.
	 *
	 * @return the company ID of this premios
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this premios.
	 *
	 * @param companyId the company ID of this premios
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this premios.
	 *
	 * @return the user ID of this premios
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this premios.
	 *
	 * @param userId the user ID of this premios
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this premios.
	 *
	 * @return the user uuid of this premios
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this premios.
	 *
	 * @param userUuid the user uuid of this premios
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this premios.
	 *
	 * @return the user name of this premios
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this premios.
	 *
	 * @param userName the user name of this premios
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this premios.
	 *
	 * @return the create date of this premios
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this premios.
	 *
	 * @param createDate the create date of this premios
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this premios.
	 *
	 * @return the modified date of this premios
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this premios.
	 *
	 * @param modifiedDate the modified date of this premios
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this premios.
	 *
	 * @return the nome of this premios
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this premios.
	 *
	 * @param nome the nome of this premios
	 */
	public void setNome(String nome);

	/**
	 * Returns the descricao of this premios.
	 *
	 * @return the descricao of this premios
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this premios.
	 *
	 * @param descricao the descricao of this premios
	 */
	public void setDescricao(String descricao);

	/**
	 * Returns the file entry ID of this premios.
	 *
	 * @return the file entry ID of this premios
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this premios.
	 *
	 * @param fileEntryId the file entry ID of this premios
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the file url of this premios.
	 *
	 * @return the file url of this premios
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this premios.
	 *
	 * @param fileUrl the file url of this premios
	 */
	public void setFileUrl(String fileUrl);

}