/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.vertigo.estagio.campanha.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Promocao service. Represents a row in the &quot;FOO_Promocao&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.vertigo.estagio.campanha.model.impl.PromocaoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.vertigo.estagio.campanha.model.impl.PromocaoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Promocao
 * @generated
 */
@ProviderType
public interface PromocaoModel
	extends BaseModel<Promocao>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a promocao model instance should use the {@link Promocao} interface instead.
	 */

	/**
	 * Returns the primary key of this promocao.
	 *
	 * @return the primary key of this promocao
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this promocao.
	 *
	 * @param primaryKey the primary key of this promocao
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this promocao.
	 *
	 * @return the uuid of this promocao
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this promocao.
	 *
	 * @param uuid the uuid of this promocao
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the promocao ID of this promocao.
	 *
	 * @return the promocao ID of this promocao
	 */
	public long getPromocaoId();

	/**
	 * Sets the promocao ID of this promocao.
	 *
	 * @param promocaoId the promocao ID of this promocao
	 */
	public void setPromocaoId(long promocaoId);

	/**
	 * Returns the group ID of this promocao.
	 *
	 * @return the group ID of this promocao
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this promocao.
	 *
	 * @param groupId the group ID of this promocao
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this promocao.
	 *
	 * @return the company ID of this promocao
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this promocao.
	 *
	 * @param companyId the company ID of this promocao
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this promocao.
	 *
	 * @return the user ID of this promocao
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this promocao.
	 *
	 * @param userId the user ID of this promocao
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this promocao.
	 *
	 * @return the user uuid of this promocao
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this promocao.
	 *
	 * @param userUuid the user uuid of this promocao
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this promocao.
	 *
	 * @return the user name of this promocao
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this promocao.
	 *
	 * @param userName the user name of this promocao
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this promocao.
	 *
	 * @return the create date of this promocao
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this promocao.
	 *
	 * @param createDate the create date of this promocao
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this promocao.
	 *
	 * @return the modified date of this promocao
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this promocao.
	 *
	 * @param modifiedDate the modified date of this promocao
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this promocao.
	 *
	 * @return the nome of this promocao
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this promocao.
	 *
	 * @param nome the nome of this promocao
	 */
	public void setNome(String nome);

	/**
	 * Returns the descricao of this promocao.
	 *
	 * @return the descricao of this promocao
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this promocao.
	 *
	 * @param descricao the descricao of this promocao
	 */
	public void setDescricao(String descricao);

	/**
	 * Returns the file entry ID of this promocao.
	 *
	 * @return the file entry ID of this promocao
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this promocao.
	 *
	 * @param fileEntryId the file entry ID of this promocao
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the file url of this promocao.
	 *
	 * @return the file url of this promocao
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this promocao.
	 *
	 * @param fileUrl the file url of this promocao
	 */
	public void setFileUrl(String fileUrl);

	/**
	 * Returns the premio ID of this promocao.
	 *
	 * @return the premio ID of this promocao
	 */
	public long getPremioId();

	/**
	 * Sets the premio ID of this promocao.
	 *
	 * @param premioId the premio ID of this promocao
	 */
	public void setPremioId(long premioId);

	/**
	 * Returns the data inicio of this promocao.
	 *
	 * @return the data inicio of this promocao
	 */
	public Date getDataInicio();

	/**
	 * Sets the data inicio of this promocao.
	 *
	 * @param dataInicio the data inicio of this promocao
	 */
	public void setDataInicio(Date dataInicio);

	/**
	 * Returns the data termino of this promocao.
	 *
	 * @return the data termino of this promocao
	 */
	public Date getDataTermino();

	/**
	 * Sets the data termino of this promocao.
	 *
	 * @param dataTermino the data termino of this promocao
	 */
	public void setDataTermino(Date dataTermino);

	/**
	 * Returns the sorteado of this promocao.
	 *
	 * @return the sorteado of this promocao
	 */
	public boolean getSorteado();

	/**
	 * Returns <code>true</code> if this promocao is sorteado.
	 *
	 * @return <code>true</code> if this promocao is sorteado; <code>false</code> otherwise
	 */
	public boolean isSorteado();

	/**
	 * Sets whether this promocao is sorteado.
	 *
	 * @param sorteado the sorteado of this promocao
	 */
	public void setSorteado(boolean sorteado);

}